---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: accountservice
  name: accountservice
  namespace: dapreshop
  resourceVersion: '153364'
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: accountservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: accountservice
        dapr.io/app-port: '80'
        dapr.io/config: zipkin
        dapr.io/enabled: 'true'
      creationTimestamp: null
      labels:
        app: accountservice
        version: v1
    spec:
      containers:
        - env:
            - name: Logging__Console__FormatterName
          image: 'accountservice:release'
          imagePullPolicy: Never
          name: web
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

